### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by acabal** [samisiddiqui/whenGodLaughsAndOtherStories-JackLondon#1]
Endnotes

- Missing period in endnote 1. Is that a book name? If so italics are needed.
- Lint fails here, due to the trailing punctuation.

The Chinago

- Remove z3998:verse semantic from `<cite>` tag. A citation is not verse.

Just Meat

- Double quotes instead of single quotes in title. Remember to change `<h2>`, `<title>`, and ToC.
- Kibosh does not need italics, remove them

Make Westing

- Remove `<i>` tag and z3998:verse semantic from `<cite>` tag. A citation is not verse and the citation is not a book either.

The Francis Spaight

- Remove quotes from `<title>`, `<h2>`, and ToC. In `<h2>` switch to italics with semantics for ship name.

"When God Laughs"

- unnecessary comment below header
- you removed mid-sentence capitals in the epigraph, but those were there because those were actually lines of a poem. You should re-add the capitals and switch to poetry formatting for the epigraph.

**Comment by acabal** [comment]
Large number of miscurled single quotation marks. Use this regex to find candidates to review: `\s‘[a-z]`

**Comment by acabal** [comment]
In colophon, remove comma after "Les Bowler"

**Comment by acabal** [comment]
In colophon, correct SE identifier URL to match the one in content.opf (without subtitle)

**Comment by acabal** [comment]
In content.opf, long-description is missing a closing `<p>` tag.

**Comment by acabal** [comment]
Cover image and title image are not using our new standard template. I suggest you create a temp folder and run `create-draft` to have it generate the correct cover and title page image templates, and copy them in. Remember to run `build-images` afterwards.

**Comment by acabal** [comment]
You did not include the original producer, Matt Brady, in the colophon or metadata. Make sure to include him in both places and using the correct MARC relator tags in the metadata.

**Comment by samisiddiqui** [comment]
Resolved as of https://github.com/samisiddiqui/whenGodLaughsAndOtherStories-JackLondon/commit/dca40845877909b42c533ba31debb87050333d70
