### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by acabal** [samisiddiqui/whenGodLaughsAndOtherStories-JackLondon#2]
- in When God Laughs you are not using the correct semantic pattern for a section header with an epigraph. See https://standardebooks.org/contribute/semantics and search for "Sections with Epigraphs"
- It is not necessary to nest a blockquote within a blockquote, because the quotation is not quoting something. Remove the nested blockquote and pull the poetry semantic into the parent blockquote.
- Book reference in endnotes is missing book semantics. Did you check to see if that is actually a book? I haven't read this ebook yet so I was simply guessing.

**Comment by acabal** [comment]
Run `clean` again too before committing as it makes changes to When God Laughs

**Comment by samisiddiqui** [comment]
Okay, the first two issues have been resolved, but I'm kind of blanking out on the endnotes issue. Is that just changing `<i>` to `<i epub:type="z3998:non-fiction">` (the referenced work is a non-fiction work).

**Comment by acabal** [comment]
No; if that is an actual book, then use "se:name.publication.book". "z3998:non-fiction" implies that the contents of the tag are non-fiction content, which is not what is going on here. The contents of the tag are the name of a book.

**Comment by samisiddiqui** [comment]
Okay, I think I got everything as of https://github.com/samisiddiqui/whenGodLaughsAndOtherStories-JackLondon/commit/956dc1f47f7d0feb4bb231cbcaa99c297acab0dd
